import { describe, it, expect } from 'vitest'
import { parseGA4CSV } from '@/lib/csv/parse'
import { readFileSync } from 'fs'
import { resolve } from 'path'

function makeFile(content: string, name = 'test.csv'): File {
  return new File([content], name, { type: 'text/csv' })
}

describe('parseGA4CSV', () => {
  it('stub: function is importable without error', () => {
    // Verifies the import resolves
    const type = typeof parseGA4CSV
    if (type !== 'function') throw new Error('Expected parseGA4CSV to be a function')
  })

  it('correctly maps GA4 column names from fixture file', async () => {
    const fixturePath = resolve(__dirname, 'fixtures/ga4-sample.csv')
    const csvContent = readFileSync(fixturePath, 'utf-8')
    const file = makeFile(csvContent, 'ga4-sample.csv')

    const rows = await parseGA4CSV(file)

    expect(rows.length).toBeGreaterThan(0)
    // First row in fixture: "How to Add Instagram Feed to WordPress (Proven Guide)", 4520, 0.42
    const first = rows[0]
    expect(first.pageTitle).toBe('How to Add Instagram Feed to WordPress (Proven Guide)')
    expect(first.sessions).toBe(4520)
    expect(first.bounceRate).toBeCloseTo(0.42, 2)
  })

  it('handles GA4 metadata header rows — skips comment lines starting with #', async () => {
    const csvWithMetadata = `# Google Analytics 4 Report: Pages and screens
# Property: Smash Balloon (123456789)
# Date range: Jan 1, 2025 - Jan 31, 2025
# Report: Pages and screens
# Segment: All Users
# Filter: None
# Metrics: Sessions, Bounce rate
#
# Note: This report was automatically generated by Google Analytics 4

Page title,Sessions,Bounce rate
Article One,100,0.50
Article Two,200,0.30
`
    const file = makeFile(csvWithMetadata)
    const rows = await parseGA4CSV(file)

    expect(rows.length).toBe(2)
    expect(rows[0].pageTitle).toBe('Article One')
    expect(rows[0].sessions).toBe(100)
    expect(rows[1].pageTitle).toBe('Article Two')
    expect(rows[1].sessions).toBe(200)
  })

  it('filters out rows with empty pageTitle', async () => {
    const csv = `Page title,Sessions,Bounce rate
Good Article,500,0.40
,300,0.50
Another Good Article,200,0.60
`
    const file = makeFile(csv)
    const rows = await parseGA4CSV(file)

    expect(rows.length).toBe(2)
    expect(rows.every(r => r.pageTitle.trim().length > 0)).toBe(true)
  })

  it('filters out rows with non-numeric sessions', async () => {
    const csv = `Page title,Sessions,Bounce rate
Good Article,500,0.40
Bad Row,abc,0.50
Another Good Article,200,0.60
`
    const file = makeFile(csv)
    const rows = await parseGA4CSV(file)

    expect(rows.length).toBe(2)
  })

  it('returns empty array for a CSV with only metadata rows and no data rows', async () => {
    const csv = `# This is only metadata
# Nothing here
# No column header row
`
    const file = makeFile(csv)
    const rows = await parseGA4CSV(file)

    expect(rows).toEqual([])
  })
})
